GET http://localhost:3000/users
###
GET http://localhost:3000/users/1
###
POST http://localhost:3000/users
Content-Type: application/json

{
    "first_name": "Angel",
    "last_name": "Vidal",
    "email": "vidal03@gmail.com",
    "password": "vidal12345"
}

###
PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "first_name": "David",
    "last_name": "Cabrera",
    "email": "vidal03@gmail.com"
}
###
DELETE http://localhost:3000/users/2